name: Python CI/CD with Tests and Linting 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-test-lint: 
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.10']

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' 

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip # Atualiza o pip
        pip install pylint # Instala o Pylint, pois será usado nesta etapa

    - name: Run unit tests 
      run: python -m unittest discover -s . -p "test_*.py"

    - name: Analyze code with Pylint 
      run: |
        pylint $(git ls-files '*.py') # Executa o Pylint em todos os arquivos .py do repositório
      continue-on-error: true 